[package]
name = "rokmu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libadwaita = "0.1.1"
gtk4 = { version = "0.4.8", features = ["v4_6"] }
gdk4 = "0.4.8"
glib = "0.15.12"
curl = "0.4.43"
